export const vehiclesData = {
  VehicleMake: [
    { id: 1, name: "Bayerische Motoren Werke", abrv: "BMW" },
    { id: 2, name: "Mercedes-Benz", abrv: "Mercedes" },
    { id: 3, name: "Toyota Motor Corporation", abrv: "Toyota" },
    { id: 4, name: "Audi AG", abrv: "Audi" },
    { id: 5, name: "Ford Motor Company", abrv: "Ford" },
    { id: 6, name: "Chevrolet", abrv: "Chevy" },
    { id: 7, name: "Honda Motor Co.", abrv: "Honda" },
    { id: 8, name: "Nissan Motor Co.", abrv: "Nissan" },
    { id: 9, name: "Hyundai Motor Company", abrv: "Hyundai" },
    { id: 10, name: "Kia Corporation", abrv: "Kia" },
    { id: 11, name: "Volkswagen AG", abrv: "VW" },
    { id: 12, name: "Subaru Corporation", abrv: "Subaru" },
    { id: 13, name: "Mazda Motor Corporation", abrv: "Mazda" },
    { id: 14, name: "Lexus", abrv: "Lexus" },
    { id: 15, name: "Dr. Ing. h.c. F. Porsche AG", abrv: "Porsche" },
  ],
  VehicleModel: [
    { id: 1, makeid: 10, name: "Soul", abrv: "Soul" },
    { id: 2, makeid: 6, name: "Impala", abrv: "Impala" },
    { id: 3, makeid: 2, name: "E400", abrv: "E400" },
    { id: 4, makeid: 3, name: "Supra", abrv: "Supra" },
    { id: 5, makeid: 7, name: "Pilot", abrv: "Pilot" },
    { id: 6, makeid: 1, name: "M3", abrv: "M3" },
    { id: 7, makeid: 3, name: "Rav4", abrv: "Rav4" },
    { id: 8, makeid: 10, name: "Optima", abrv: "Optima" },
    { id: 9, makeid: 4, name: "A6", abrv: "A6" },
    { id: 10, makeid: 5, name: "Mustang", abrv: "Mustang" },
    { id: 11, makeid: 7, name: "CR-V", abrv: "CR-V" },
    { id: 12, makeid: 8, name: "Rogue", abrv: "Rogue" },
    { id: 13, makeid: 1, name: "i8", abrv: "i8" },
    { id: 14, makeid: 9, name: "Elantra", abrv: "Elantra" },
    { id: 15, makeid: 3, name: "Corolla", abrv: "Corolla" },
    { id: 16, makeid: 2, name: "E63 AMG", abrv: "E63 AMG" },
    { id: 17, makeid: 6, name: "Malibu", abrv: "Malibu" },
    { id: 18, makeid: 8, name: "Maxima", abrv: "Maxima" },
    { id: 19, makeid: 6, name: "Equinox", abrv: "Equinox" },
    { id: 20, makeid: 5, name: "Escape", abrv: "Escape" },
    { id: 21, makeid: 3, name: "GT-86", abrv: "GT-86" },
    { id: 22, makeid: 7, name: "Accord", abrv: "Accord" },
    { id: 23, makeid: 5, name: "Focus", abrv: "Focus" },
    { id: 24, makeid: 9, name: "Sonata", abrv: "Sonata" },
    { id: 25, makeid: 1, name: "420d", abrv: "420d" },
    { id: 26, makeid: 9, name: "Santa Fe", abrv: "Santa Fe" },
    { id: 27, makeid: 4, name: "A4", abrv: "A4" },
    { id: 28, makeid: 10, name: "Sportage", abrv: "Sportage" },
    { id: 29, makeid: 5, name: "F-150", abrv: "F-150" },
    { id: 30, makeid: 9, name: "Kona", abrv: "Kona" },
    { id: 31, makeid: 3, name: "Camry", abrv: "Camry" },
    { id: 32, makeid: 6, name: "Camaro", abrv: "Camaro" },
    { id: 33, makeid: 7, name: "Fit", abrv: "Fit" },
    { id: 34, makeid: 4, name: "R8", abrv: "R8" },
    { id: 35, makeid: 2, name: "E200", abrv: "E200" },
    { id: 36, makeid: 7, name: "Civic", abrv: "Civic" },
    { id: 37, makeid: 8, name: "Leaf", abrv: "Leaf" },
    { id: 38, makeid: 2, name: "E300", abrv: "E300" },
    { id: 39, makeid: 10, name: "Sorento", abrv: "Sorento" },
    { id: 40, makeid: 8, name: "Sentra", abrv: "Sentra" },
    { id: 41, makeid: 9, name: "Tucson", abrv: "Tucson" },
    { id: 42, makeid: 6, name: "Silverado", abrv: "Silverado" },
    { id: 43, makeid: 1, name: "X5", abrv: "X5" },
    { id: 44, makeid: 4, name: "TT", abrv: "TT" },
    { id: 45, makeid: 4, name: "Q5", abrv: "Q5" },
    { id: 46, makeid: 2, name: "C300d", abrv: "C300d" },
    { id: 47, makeid: 1, name: "740i", abrv: "740i" },
    { id: 48, makeid: 5, name: "Escape", abrv: "Escape" },
    { id: 49, makeid: 8, name: "Altima", abrv: "Altima" },
    { id: 50, makeid: 10, name: "Forte", abrv: "Forte" },
    { id: 51, makeid: 15, name: "Taycan", abrv: "Taycan" },
    { id: 52, makeid: 11, name: "Jetta", abrv: "Jetta" },
    { id: 53, makeid: 12, name: "BRZ", abrv: "BRZ" },
    { id: 54, makeid: 14, name: "IS", abrv: "IS" },
    { id: 55, makeid: 12, name: "Outback", abrv: "Outback" },
    { id: 56, makeid: 13, name: "Mazda6", abrv: "Mazda6" },
    { id: 57, makeid: 14, name: "RX", abrv: "RX" },
    { id: 58, makeid: 15, name: "911 Carrera", abrv: "911" },
    { id: 59, makeid: 11, name: "Arteon", abrv: "Arteon" },
    { id: 60, makeid: 13, name: "CX-5", abrv: "CX-5" },
    { id: 61, makeid: 15, name: "Macan", abrv: "Macan" },
    { id: 62, makeid: 11, name: "Tiguan", abrv: "Tiguan" },
    { id: 63, makeid: 13, name: "CX-9", abrv: "CX-9" },
    { id: 64, makeid: 14, name: "NX", abrv: "NX" },
    { id: 65, makeid: 15, name: "Panamera", abrv: "Panamera" },
    { id: 66, makeid: 12, name: "Legacy", abrv: "Legacy" },
    { id: 67, makeid: 13, name: "Mazda3", abrv: "Mazda3" },
    { id: 68, makeid: 14, name: "ES", abrv: "ES" },
    { id: 69, makeid: 15, name: "Cayman", abrv: "Cayman" },
    { id: 70, makeid: 12, name: "Impreza", abrv: "Impreza" },
    { id: 71, makeid: 14, name: "UX", abrv: "UX" },
    { id: 72, makeid: 13, name: "MX-5", abrv: "MX-5" },
    { id: 73, makeid: 12, name: "Forester", abrv: "Forester" },
    { id: 74, makeid: 11, name: "Passat", abrv: "Passat" },
    { id: 75, makeid: 11, name: "Golf", abrv: "Golf" },
  ],
};
